package bean;

import java.math.BigDecimal;

/**
 * Combo generated by hbm2java
 */
public class Combo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maCombo;
	private String tenCombo;
	private BigDecimal giaTien;
	private String moTa;
	private byte[] hinhAnhMoTa;

	public Combo() {
	}

	public Combo(String maCombo) {
		this.maCombo = maCombo;
	}

	public Combo(String maCombo, String tenCombo, BigDecimal giaTien, String moTa, byte[] hinhAnhMoTa)
	{
		this.maCombo = maCombo;
		this.tenCombo = tenCombo;
		this.giaTien = giaTien;
		this.moTa = moTa;
		this.hinhAnhMoTa = hinhAnhMoTa;
	}

	public String getMaCombo() {
		return this.maCombo;
	}

	public void setMaCombo(String maCombo) {
		this.maCombo = maCombo;
	}

	public String getTenCombo() {
		return this.tenCombo;
	}

	public void setTenCombo(String tenCombo) {
		this.tenCombo = tenCombo;
	}

	public BigDecimal getGiaTien() {
		return this.giaTien;
	}

	public void setGiaTien(BigDecimal giaTien) {
		this.giaTien = giaTien;
	}

	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	public byte[] getHinhAnhMoTa() {
		return this.hinhAnhMoTa;
	}

	public void setHinhAnhMoTa(byte[] hinhAnhMoTa) {
		this.hinhAnhMoTa = hinhAnhMoTa;
	}

}
