package bean;

import java.awt.Checkbox;

/**
 * DoTrongGioHang generated by hbm2java
 */
public class DoTrongGioHang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private KhoaHoc item;
	private String check;
	
	public DoTrongGioHang() {
	}

	public DoTrongGioHang(String id) {
		this.item = new KhoaHoc(id);
		this.check="";
	}
	
	public KhoaHoc getItem() {
		return this.item;
	}

	public void setItem(KhoaHoc id) {
		this.item = id;
	}

	public String getCheck() {
		return this.check;
	}

	public void setCheck(String check) {
		this.check = check;
	}
	
}
