package bean;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * GioHang generated by hbm2java
 */
public class GioHang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maGioHang;
	private HocVien hocVien;
	private Integer soLuongHienTai;
	private List<DoTrongGioHang> doTrongGioHangs;

	public GioHang() {
	}

	public GioHang(String maGioHang) {
		this.maGioHang = maGioHang;
	}

	public GioHang(String maGioHang, HocVien hocVien, Integer soLuongHienTai, List<DoTrongGioHang> doTrongGioHangs) {
		this.maGioHang = maGioHang;
		this.hocVien = hocVien;
		this.soLuongHienTai = soLuongHienTai;
		this.doTrongGioHangs = doTrongGioHangs;
	}

	public String getMaGioHang() {
		return this.maGioHang;
	}

	public void setMaGioHang(String maGioHang) {
		this.maGioHang = maGioHang;
	}

	public HocVien getHocVien() {
		return this.hocVien;
	}

	public void setHocVien(HocVien hocVien) {
		this.hocVien = hocVien;
	}

	public Integer getSoLuongHienTai() {
		return this.soLuongHienTai;
	}

	public void setSoLuongHienTai(Integer soLuongHienTai) {
		this.soLuongHienTai = soLuongHienTai;
	}

	public List<DoTrongGioHang> getDoTrongGioHangs() {
		return this.doTrongGioHangs;
	}

	public void setDoTrongGioHangs(List<DoTrongGioHang> doTrongGioHangs) {
		this.doTrongGioHangs.addAll(doTrongGioHangs);
	}

}
