package bean;


/**
 * KhoiLop generated by hbm2java
 */
public class KhoiLop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maKhoi;
	private String tenKhoi;
	
	public KhoiLop() {
	}

	public KhoiLop(String maKhoi) {
		this.maKhoi = maKhoi;
	}

	public KhoiLop(String maKhoi, String tenKhoi) {
		this.maKhoi = maKhoi;
		this.tenKhoi = tenKhoi;
		
	}

	public String getMaKhoi() {
		return this.maKhoi;
	}

	public void setMaKhoi(String maKhoi) {
		this.maKhoi = maKhoi;
	}

	public String getTenKhoi() {
		return this.tenKhoi;
	}

	public void setTenKhoi(String tenKhoi) {
		this.tenKhoi = tenKhoi;
	}
}
