package bean;
/**
 * Mon generated by hbm2java
 */
public class Mon implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maMon;
	private String tenMon;
	

	public Mon() {
	}

	public Mon(String maMon) {
		this.maMon = maMon;
	}

	public Mon(String maMon, String tenMon) {
		this.maMon = maMon;
		this.tenMon = tenMon;
		
	}

	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

}
