package bean;
// Generated Dec 3, 2022, 12:48:29 PM by Hibernate Tools 6.0.2.Final

import java.util.List;

/**
 * QuanTriVien generated by hbm2java
 */
public class QuanTriVien implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maQtv;
	private String hoTen;
	private String sdt;
	private String email;
	private String diaChi;
	private String cccd;
	private List<PhanMon> phanMons;

	public QuanTriVien() {
	}

	public QuanTriVien(String maQtv) {
		this.maQtv = maQtv;
	}

	public QuanTriVien(String maQtv, String hoTen, String sdt, String email, String diaChi, String cccd,
		List<PhanMon> phanMon) {
		this.maQtv = maQtv;
		this.hoTen = hoTen;
		this.sdt = sdt;
		this.email = email;
		this.diaChi = diaChi;
		this.cccd = cccd;
		this.phanMons = phanMon;
	}

	public String getMaQtv() {
		return this.maQtv;
	}

	public void setMaQtv(String maQtv) {
		this.maQtv = maQtv;
	}

	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public String getCccd() {
		return this.cccd;
	}

	public void setCccd(String cccd) {
		this.cccd = cccd;
	}

	public List<PhanMon> getPhanMon() {
		return this.phanMons;
	}

	public void setPhanMon(List<PhanMon> phanMon) {
		this.phanMons.addAll(phanMon);
	}

	
}
