package bean;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import dao.ConnectDataBase;

/**
 * ViThanhToan generated by hbm2java
 */
public class ViThanhToan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String maVi;
	private String hocVien;
	private int soDu;
	private Date ngayCapNhat;

	public ViThanhToan() {
	}

	public ViThanhToan(String maVi, String hocVien, int soDu, Date ngayCapNhat) 
	{	
		this.maVi = maVi;
		this.hocVien = hocVien;
		this.soDu = soDu;
		this.ngayCapNhat = ngayCapNhat;
	}
	
	public String autoID(Connection conn) throws SQLException
	{
		String sql = "SELECT COUNT(*) as SoLuong FROM ViThanhToan";
		
		PreparedStatement pstm=null;
		try {
			pstm = conn.prepareStatement(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        ResultSet rs = pstm.executeQuery();
        String kqString="";
        while (rs.next()) 
        {
        	int soluong = rs.getInt("SoLuong");
        	if (soluong+1<10)
        		kqString= "VTT000"+ String.valueOf(soluong+1);
        	else {
				kqString= "VTT00"+ String.valueOf(soluong+1);
			}
        }
        return kqString;  
	}

	
	public ViThanhToan(Connection conn,String hocVien, int soDu, Date ngayCapNhat) throws SQLException 
	{	
		this.maVi = autoID(conn);
		this.hocVien = hocVien;
		this.soDu = soDu;
		this.ngayCapNhat = ngayCapNhat;
	}
	
	

	public String getMaVi() {
		return this.maVi;
	}

	public void setMaVi(String maVi) {
		this.maVi = maVi;
	}

	public String getHocVien()
	{
		return this.hocVien;
	}

	public void setHocVien(String hocVien)
	{
		this.hocVien = hocVien;
	}

	public int getSoDu() {
		return this.soDu;
	}

	public void setSoDu(int soDu) {
		this.soDu = soDu;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}
	
	public void LayVi(Connection conn,String maHocVien) throws SQLException 
	{	
        String sql = "Select * from ViThanhToan where MaHocVien=?";
        PreparedStatement pstm = conn.prepareStatement(sql);
        pstm.setString(1, maHocVien);
        ResultSet rs = pstm.executeQuery();
        
        String maVi;
        BigDecimal soDu;
        
        while (rs.next()) 
        {
        	maVi=rs.getString("MaVi");
        	soDu=rs.getBigDecimal("SoDu");
	    	this.hocVien=maHocVien;
	    	this.maVi=maVi;
	    	this.soDu=soDu.intValue();
        }
    }
	
	public ViThanhToan(Connection conn,String maHocVien) throws SQLException {
		LayVi(conn, maHocVien);
	}
	
	public void PhatSinhGiaoDich(Connection conn,String maHoaDon, int sotien) throws SQLException 
	{	
        String sql = "Insert into GiaoDich values(?, ?, ?, ?, ?, ?)";
        PreparedStatement pstm = conn.prepareStatement(sql);
        pstm.setString(1, maHoaDon);
        pstm.setBigDecimal(2, BigDecimal.valueOf(sotien));
        pstm.setString(3, "Đăng ký khóa học");
        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);
        pstm.setDate(4,date);
        pstm.setBigDecimal(5,BigDecimal.valueOf(this.soDu));
        pstm.setString(6, this.maVi);
        pstm.executeUpdate();
    }
}
